title: Beatrice Venckute
description: A website with a blog
footer_text: Copyright 2021 Beatrice Venckute
header_feature_image: ../uploads/screenshot-2021-10-12-at-16.02.45.png
header_text: Hungry Types
header_text_color: "#ffffff"
bannerheight: 20vmax
navbarheight: 55px
logo: /uploads/logo.jpg
favicon: ../uploads/2020-12-12-19_49_50.781-0200_mh1.jpg
gridlayout: false
fixednavbar: false
upzoom: true
