title: Beatrice for Brookes
description: A website with a blog
footer_text: Copyright 2021 Beatrice Venckute
header_feature_image: ../uploads/untitled-design.png
header_text: ""
header_text_color: ""
bannerheight: 20vmax
navbarheight: 55px
logo: ../uploads/hungry-types.png
favicon: ../uploads/hungry-types.png
gridlayout: true
fixednavbar: false
upzoom: true
