title: Beatrice Venckute
description: A website with a blog
footer_text: Copyright 2021 Beatrice Venckute
header_feature_image: ../uploads/arthur-edelmans-34de2rovp_i-unsplash.jpg
header_text: Hungry Types
header_text_color: "#ffffff"
bannerheight: 20vmax
navbarheight: 55px
logo: ../uploads/2020-12-12-19_49_50.781-0200_mh1-modified.png
favicon: ../uploads/2020-12-12-19_49_50.781-0200_mh1-modified.png
gridlayout: false
fixednavbar: false
upzoom: true
