title: Beatrice for Brookes
description: A website with a blog
footer_text: Copyright 2021 Beatrice Venckute
header_feature_image: ../uploads/untitled-design.png
header_text: Hungry Types
header_text_color: "#ffffff"
bannerheight: 20vmax
navbarheight: 55px
logo: ../uploads/hungry-types.png
favicon: ../uploads/hungry-types.png
gridlayout: false
fixednavbar: false
upzoom: true
